// The arena: a shrinking voxel platform over a per-map environmental hazard
// (lava sea, ocean, toxic swamp, sharp rocks, or arcane abyss).
// Owns both the logical radius (used by the simulation) and the visuals.
// Also holds a MapQuery that exposes height/collision queries for the
// procedural layout generated by mapgen.js and broadcast to clients.
import * as THREE from "three";
import { CFG, getArenaWorld, getArenaHazard, isOnArenaWorld } from "./config.js";
import { buildPlatform, buildHazard, animateHazard, buildHazardDetails, animateHazardDetails } from "./voxel.js";
import { MapQuery } from "./arena-query.js";
import type { ArenaWorld, ArenaHazard, MapLayout } from "./types";

export class Arena {
  scene: THREE.Scene;
  world: ArenaWorld;
  hazard: ArenaHazard;
  radius: number;
  _builtRadius: number;
  _builtWorld: string | null;
  platform: THREE.Group | null;
  lava: THREE.Mesh | null; // current hazard surface (kept as `lava` for callers)
  details: THREE.Group | null; // ambient detail props floating over the hazard
  _query: MapQuery;

  constructor(scene: THREE.Scene) {
    this.scene = scene;
    this.world = getArenaWorld(CFG.DEFAULT_ARENA_WORLD);
    this.hazard = getArenaHazard(this.world.id);
    this.radius = CFG.ARENA_RADIUS;
    this._builtRadius = -1;
    this._builtWorld = null;
    this.platform = null;
    this.lava = null; // current hazard surface (kept as `lava` for callers)
    this.details = null; // ambient detail props floating over the hazard
    // Layout query — set from the round-start mapLayout payload via setLayout().
    this._query = new MapQuery(null);
    this._buildHazard();
    this.rebuild();
  }

  // (Re)build the themed hazard surface (and its ambient detail props) and swap
  // them into the scene, disposing the previous ones to avoid GPU leaks.
  _buildHazard(): void {
    this.hazard = getArenaHazard(this.world.id);
    if (this.lava) {
      this.scene.remove(this.lava);
      this.lava.geometry?.dispose?.();
      (this.lava.material as THREE.Material)?.dispose?.();
    }
    if (this.details) {
      this.scene.remove(this.details);
      this.details.traverse((o) => {
        const mesh = o as THREE.Mesh;
        if (mesh.geometry) mesh.geometry.dispose?.();
        if (mesh.material) (mesh.material as THREE.Material).dispose?.();
      });
    }
    this.lava = buildHazard(160, CFG.LAVA_Y, this.hazard);
    this.scene.add(this.lava);
    this.details = buildHazardDetails(160, CFG.LAVA_Y, this.hazard);
    this.scene.add(this.details);
  }

  setWorld(worldId: string): void {
    const world = getArenaWorld(worldId);
    if (world.id === this.world.id) return;
    this.world = world;
    this._buildHazard();
    this.rebuild();
  }

  setRadius(r: number): void {
    this.radius = Math.max(CFG.ARENA_MIN_RADIUS, r);
    // Only rebuild the (relatively expensive) mesh when it changed meaningfully.
    if (Math.abs(this.radius - this._builtRadius) >= 0.75 || this.world.id !== this._builtWorld) this.rebuild();
  }

  rebuild(): void {
    if (this.platform) {
      this.scene.remove(this.platform);
      this.platform.traverse((o) => {
        const mesh = o as THREE.Mesh;
        if (mesh.geometry) mesh.geometry.dispose();
        if (mesh.material) (mesh.material as THREE.Material).dispose?.();
      });
    }
    this.platform = buildPlatform(this.radius, this.world.id);
    this.scene.add(this.platform);
    this._builtRadius = this.radius;
    this._builtWorld = this.world.id;
  }

  // Is a point (x,z) still on solid ground?
  isOnPlatform(x: number, z: number): boolean {
    return isOnArenaWorld(this.world.id, this.radius, x, z);
  }

  // ---- Map layout query layer -----------------------------------------------
  // Called by the renderer (main.js / net.js) when the host broadcasts the
  // round-start mapLayout.  Stores the layout and exposes height/collision queries
  // so the renderer can do height-based effects and future sim phases can add
  // movement/projectile blocking.

  /**
   * Store the procedural map layout generated by mapgen.generateMap() and
   * broadcast in the MSG.START payload.  Pass null to clear (round end / reset).
   */
  setLayout(layout: MapLayout | null): void {
    this._query.setLayout(layout);
  }

  /**
   * Ground height at (x, z).
   * Returns CFG.PLATFORM_TOP (0) on the base platform, plateau height when over
   * a plateau top, or linearly interpolated when over a ramp footprint.
   */
  groundHeightAt(x: number, z: number): number { return this._query.groundHeightAt(x, z); }

  /**
   * True when (x, z) is inside a plateau wall or obstacle circle that is
   * meaningfully above fromY and not reachable via a ramp.
   */
  blocksMovement(x: number, z: number, fromY: number): boolean { return this._query.blocksMovement(x, z, fromY); }

  /**
   * True when the line segment (x0,z0,y0)→(x1,z1,y1) is blocked by a plateau
   * wall or obstacle (used by projectiles and direct-hit spells).
   */
  obstaclesBlockingRay(x0: number, z0: number, y0: number, x1: number, z1: number, y1: number): boolean {
    return this._query.obstaclesBlockingRay(x0, z0, y0, x1, z1, y1);
  }

  /**
   * True when (x, z) is inside a ramp footprint.  Used by player.js to avoid
   * triggering free-fall / fall-stun while the player is descending a ramp.
   */
  onRamp(x: number, z: number): boolean { return this._query.onRamp(x, z); }

  update(t: number, dt: number): void {
    animateHazard(this.lava, t);
    animateHazardDetails(this.details, t, dt);
  }

  reset(radius: number = CFG.ARENA_RADIUS, worldId: string = CFG.DEFAULT_ARENA_WORLD): void {
    const world = getArenaWorld(worldId);
    const worldChanged = world.id !== this.world.id;
    this.world = world;
    this.radius = radius;
    if (worldChanged || !this.lava) this._buildHazard();
    this.rebuild();
    this._query.setLayout(null); // clear layout on reset; caller sets it again at round start
  }
}
